[tool.pyright]
typeCheckingMode = "strict"
include = ["."]

[tool.mypy]
python_version = "3.10"
disallow_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
warn_unused_configs = true
